# test-pod.yaml 修正
apiVersion: v1
kind: Pod
metadata:
  annotations:
    requires-gpu-model: A100
  name: test-with-custom-filter
  namespace: web
spec:
  schedulerName: custom-filter-scheduler
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.9
